# -*- coding: utf-8 -*-
"""EMAIL_ASSISTANT_API

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mz_vFZfih72yRDGzFtdQ6Sys1fcogvxZ
"""

!pip install langchain-google-genai langchain-core langgraph pydantic --quiet

import os
from typing import Annotated, TypedDict, Union, Literal
from langchain_google_genai import ChatGoogleGenerativeAI
from langchain_core.messages import BaseMessage, HumanMessage, AIMessage, ToolMessage
from langchain_core.tools import tool
from langgraph.graph import StateGraph, START, END
from langgraph.prebuilt import ToolNode
from langgraph.checkpoint.memory import MemorySaver
from pydantic import BaseModel, Field

import os
import google.generativeai as genai
genai.configure(api_key=os.environ["GOOGLE_API_KEY"])

for m in genai.list_models():
    print(m.name)